set -g mouse on
set -g default-terminal "tmux-256color"
set -g status-style bg=#000000,fg=#cfcfcf
set -g window-status-style bg=#000000,fg=#7a7a7a
set -g window-status-current-style bg=#000000,fg=#ffffff,bold
